# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Audimus.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'Audimus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rAudimus.proto\x12\x07\x61udimus\"&\n\x13\x41pplication_Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"z\n\x14Presentation_Message\x12\x11\n\tkey_epoch\x18\x01 \x01(\x05\x12\x16\n\x0esession_number\x18\x02 \x01(\x05\x12\x1b\n\x13\x61pplication_message\x18\x03 \x01(\x0c\x12\x1a\n\x12\x61uthentication_tag\x18\x04 \x01(\x0c\"\x0e\n\x0cSession_Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Audimus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATION_MESSAGE']._serialized_start=26
  _globals['_APPLICATION_MESSAGE']._serialized_end=64
  _globals['_PRESENTATION_MESSAGE']._serialized_start=66
  _globals['_PRESENTATION_MESSAGE']._serialized_end=188
  _globals['_SESSION_DATA']._serialized_start=190
  _globals['_SESSION_DATA']._serialized_end=204
# @@protoc_insertion_point(module_scope)
